### ISSUE TITLE
loading of print layout templates from configuration file

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/QgisModelBaker#595]
It should be possible to load additional print layouts templates (.qpt files) from configuration file

**Comment by signedav** [comment]
## PyQGIS and structure notes

### Storing templates:
```py
# printLayouts() only listing the print layouts `layouts` instead would list the reports as well
for layout in manager.printLayouts():
  # clarify what needs to be set in the QgsReadWriteContext()
  layout.saveAsTemplate(f"/home/cheapdave/qgis_projects/{layout.name()}.qpt",QgsReadWriteContext())
```

**Reports will not be supported in this context. Reports would have templates for every section - means one need to parse through it to store the templates (and recreate them). Maybe we can consider the structure in future.**

```yaml
layouts:
  "layout_uno" : 
    # maybe in future we will have other parameters here in future like defined items / extend etc.
    templatefile: "/home/cheapdave/qgis_projects/layout_uno.qpt"
  "layout_due" : "/home/cheapdave/qgis_projects/layout_due.qpt"
  "report one" : 
    "sectionidentifier title": "/home/cheapdave/qgis_projects/titletemplate.qpt"
    "sectionidentifier idontknow": "/home/cheapdave/qgis_projects/idontknow.qpt"
```  

 
### Recreating layouts from templates:
```py
# 1. Create the layout
layout = QgsPrintLayout( QgsProject.instance() )
#initializes default settings for blank print layout canvas
layout.initializeDefaults()  

# 2. Load template from file
template_file = "/home/cheapdave/qgis_projects/layout.qpt"
with open(template_file) as f:
  template_file_content = f.read()
doc = QDomDocument()
doc.setContent(template_file_content)
layout.loadFromTemplate(doc, QgsReadWriteContext())

# 3. Name it according the settings (mostly same name as original) if no setName the name is taken from the template file

layout.setName("layout_uno")

QgsProject.instance().layoutManager().addLayout(layout)

```
