### ISSUE TITLE
MapThemes in UsabILIty Hub

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#645]
Input from @andreasneumann
```yaml
map-themes:
  - "Karte_Detail":
      child-nodes:
          - "Vereinbarung"
          - "Orthofoto"
  - "Karte_Uebersicht":
      child-nodes:
          - "Vereinbarung"
          - "Übersichtskarte":
             style: "schwarz-weiss"
```
Beim letzten Layer "Übersichtskarte" sieht man noch optional den Style (falls es bei einem Layer mehrere Stile gibt). Die Kartenthemen können dann vom Layout referenziert werden.

**Approach A:**
Having a layertree per map theme in the YAML. We load every layertree with style and QML for each layer. And then we create a map theme from it.
```py
map_theme_record = QgsMapThemeCollection.createThemeFromCurrentState(QgsProject.instance().layerTreeRoot(),iface.layerTreeView().layerTreeModel())

QgsMapThemeCollection.insert("fancytheme", map_theme_record)
```
\- I hope not to be needed to go this approach. Because it's quite ugly to have multiple layertrees defining the same (structure). If they divert it's hard to know which one should be the one defining the structure. It's quite ugly.

**Approach B:**
Is there a way not having multpile layertrees in the YAML file? :thinking: 

```py
map_theme_record = QgsMapThemeCollection.createThemeFromCurrentState(QgsProject.instance().layerTreeRoot(),iface.layerTreeView().layerTreeModel())
```

And then store the map_theme_record. Similar to the project file:
```xml
    <visibility-preset name="Monotheme" has-expanded-info="1" has-checked-group-info="1">
      <layer style="default" expanded="1" id="Street_3ae31d05_fd8b_4e06_9d88_cb9198a7f7ee" visible="1"/>
      <expanded-legend-nodes id="Street_3ae31d05_fd8b_4e06_9d88_cb9198a7f7ee"/>
      <layer style="mono" expanded="1" id="Parks_23973047_1f26_4484_800d_3a4873190dd4" visible="1"/>
      <expanded-legend-nodes id="Parks_23973047_1f26_4484_800d_3a4873190dd4"/>
      <layer style="default" expanded="1" id="Buildings_3fcb5fb2_d0d4_4e70_ba7a_b01e00f75a18" visible="1"/>
      <expanded-legend-nodes id="Buildings_3fcb5fb2_d0d4_4e70_ba7a_b01e00f75a18"/>
      <layer style="default" expanded="1" id="Address_37cc2ab3_8db2_4826_8e40_dcd0dd17569c" visible="1"/>
      <expanded-legend-nodes id="Address_37cc2ab3_8db2_4826_8e40_dcd0dd17569c"/>
      <layer style="mono" expanded="1" id="OSM_Standard_a851f263_ace4_48f8_b7dd_1fe0f7ac19f1" visible="1"/>
      <expanded-legend-nodes id="OSM_Standard_a851f263_ace4_48f8_b7dd_1fe0f7ac19f1"/>
      <checked-group-nodes>
        <checked-group-node id="tables"/>
      </checked-group-nodes>
      <expanded-group-nodes>
        <expanded-group-node id="tables"/>
      </expanded-group-nodes>
    </visibility-preset>
```

And then we do not need to load the layer tree and then insert the current map_theme_record, but instead we make a `mapThemeRecordCreator` function to get `map_theme_record` and add it then to the collection:

```
QgsMapThemeCollection.insert("fancytheme", map_theme_record)
```

\+ for this approach is, that we can generate the mapThemeRecord and load them without creating the whole tree first
\- for this approach is, that we need to generate (and define) a new structure for storing mapThemeRecords

Either if we are able to generate `mapThemeRecords` or if we apply it to the legend (on project generation) and store it, the definition in YAML can be the same. Something like:
```yaml
mapthemes:
    - Monotheme:
        - Street:
            stylename: default
            qmlstylefile: "ilidata:themedcity_street_qml"
            visible: true
            expanded: false
        - Parks:
            stylename: mono
            qmlstylefile: "ilidata:themedcity_mono_parks_qml"
            visible: true
            expanded: false
        - Buildings:
            stylename: mono
            qmlstylefile: "ilidata:themedcity_mono_buildings_qml"
            visible: true
            expanded: false
    - Fancytheme:
        - Street:
            stylename: default
        - Parks:
            stylename: default
        - Buildings:
            stylename: fancy
            qmlstylefile: "ilidata:themedcity_fancy_buildings_qml"
            visible: true
            expanded: false
```
> If we don't define anything, then the style is the one loaded from qmlstylefile in the layertree and this is default. So it should not be listed in the mapthemes? 

**Demo files:**
[themed_city.zip](https://github.com/opengisch/QgisModelBaker/files/8313730/themed_city.zip)

**UsabILIty Hub Topping Exporter**
In the Exporter it would need a setting if the map themes should be exported. If so, then it uses the export_settings like before, but makes an export on every map-themed layer tree. How do we configure what categories should be exported? We should do it per style... :thinking: 
But export_settings are the same for all the Map Themes?

**Comment by signedav** [comment]
Some info about the possibilities.

#### Export of single styles
Even if there is in the QGIS GUI the option "Export all styles" the styles are stored in single files. Means here:
![grafik](https://user-images.githubusercontent.com/28384354/199525884-af953091-591e-4937-9284-770ebe9b240d.png)
parks_styles.qml, parks_styles_1.qml and parks_styles_2.qml would be created...

So single exports would be required anyway: 
Means it needs to `QgsMapLayerStyleManager.setCurrentStyle(nameOfStyle)` and then do the normal `saveNamedStyle`. But we need to re-set the current style in the end...

**Comment by signedav** [comment]
```yaml
layertree:
  - "Belasteter Standort":
      group: true
      checked: true
      expanded: true
      mutually-exclusive: true
      mutually-exclusive-child: 1
      child-nodes:
        - "Belasteter_Standort (Geo_Lage_Punkt)":
            featurecount: true
            qmlstylefile: "ilidata:ch.opengis.topping.opengisch_KbS_LV95_V1_4_001"
        - "Belasteter_Standort (Geo_Lage_Polygon)":
            expanded: true
            qmlstylefile: "ilidata:ch.opengis.topping.opengisch_KbS_LV95_V1_4_023

mapthemes:
    - Monotheme:
        - Street:
            stylename: default
            qmlstylefile: "ilidata:themedcity_street_qml"
            visible: true
            expanded: false
        - Parks:
            stylename: mono
            visible: true
            expanded: false
        - Buildings:
            stylename: mono
            qmlstylefile: "ilidata:themedcity_mono_buildings_qml"
            visible: true
            expanded: false
    - Fancytheme:
        - Street:
            stylename: default
        - Parks:
            stylename: default
        - Buildings:
            stylename: fancy
            qmlstylefile: "ilidata:themedcity_fancy_buildings_qml"
            visible: true
            expanded: false

```

**Comment by m-kuhn** [comment]
The concept makes sense to me.
Where is the style name defined? By convention (`qmlstylefile_[name]`) and in this case would `qmlstylefile` without name match to `Default`?
Or would we want something like this (it's more nesting but also more explicit):

```yaml
layertree:
  - "Buildings":
    featurecount: true
    styles:
      default:
        qmlstylefile: "ilidata:themedcity_buildings_qml"
      mono:
        qmlstylefile: ilidata:themedcity_mono_buildings_qml
```

**Comment by signedav** [comment]
Thanks. Yes the qmlstylefile_[name] conventi

**Comment by andreasneumann** [comment]
@signedav - can one also specify the relative path to the QML file directly, or does it always have to be registered through ilidata: first?

**Comment by signedav** [comment]
Currently we can use `file:` prefix what is relative to the tool (what should be used only for testing with Model Baker since it's mostly stored in the plugin dir of the QGIS project).

With no prefix at all I think (not sure) that a relative path to this `yaml` file inofficially works. But only locally - no url (yet)...

**Comment by andreasneumann** [comment]
> With no prefix at all I think (not sure) that a relative path to this `yaml` file inofficially works. But only locally - no url (yet)...

relative to the yaml file sounds good.

**Comment by m-kuhn** [comment]
> Currently we can use `file:` prefix what is relative to the tool (what should be used only for testing with Model Baker since it's mostly stored in the plugin dir of the QGIS project).

Can we redefine that to `tool:` or similar, I think the `file:` schema should be reserved for something useful for the end user (absolute path)

> > With no prefix at all I think (not sure) that a relative path to this `yaml` file inofficially works. But only locally - no url (yet)...
> 
> relative to the yaml file sounds good.

:+1: 

Would it make sense to split this off into a new issue?

**Comment by signedav** [comment]
Going for this structure:

**Comment by signedav** [comment]
@m-kuhn can I ask you why you choose this structure (1):
```yaml
    styles:
      default:
        qmlstylefile: "ilidata:themedcity_buildings_qml"
      mono:
        qmlstylefile: ilidata:themedcity_mono_buildings_qml
```

Alternatively you could have chosen a list (2):
```
    styles:
      - default:
          qmlstylefile: "ilidata:themedcity_buildings_qml"
      - mono:
          qmlstylefile: ilidata:themedcity_mono_buildings_qml
```

Or like this (3):
```yaml
    styles:
      - name: "default"
        qmlstylefile: "ilidata:themedcity_buildings_qml"
      - name: "mono"
        qmlstylefile: ilidata:themedcity_mono_buildings_qml
```

I'm see the differences and I have the feeling a list would be more proper (since they are equivalent items) but the dict seems straight forward to me as well. YAML allows both anyway.

Btw. (2) seems wrong to me \*, while (3) looks much better. Or (1) but there is the question if it should be more a dict-like structure or list-like.

\* Though we use it like this with the layers. Maybe this can be optimized in future. It feels there is an unused nesting too much. Having a list, but instead a dict item a one item dict with the name and then the values as assigned dict:
```py
{ "styles": 
  [ 
    { "default": 
      { "qmlstylefile" : "ilidata" }
    },
  ...
```
