### ISSUE TITLE
Hidden layers

### ISSUE THREAD

**Issue by signedav** [opengisch/QgisModelBaker#649]
> Why hidden layers are cool?
> Because you can open them via widgets (e.g. relation widgets) but don't have to see them in the legend

At the moment it's possible to hide layers generated by Model Baker from the physical database by just not adding them in the layertree structure in the project topping file (former: layertree file). Appending a QML file is possible, by mapping it to the name in the metaconfig file. 

Still the usual way to append a QML to a layer is not the metaconfig file but the layertree itself (see: #648) and there is currently no way to append an additional layer that is hidden. So it would be cool to have a proper integration like in the layertree:
```yaml
layertree:
    - "KbS_LV95_V1_4 Layers":
        group: true
        child-nodes:
            - "Belasteter_Standort (Geo_Lage_Punkt)":
              hidden: true
```

Check the implementation of the hide layer plugin for that @signedav To make it compatible with it.
